const fs=require('fs'),path=require('path'),vm=require('vm'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'arena.html'),'utf8');
const ctx=vm.createContext({console});const start=source.indexOf('var ArenaClasses='),marker="if(typeof module!=='undefined')module.exports=install;else install(root.ArenaCombat,root.ArenaClasses);",end="})(typeof window!=='undefined'?window:globalThis);";vm.runInContext(source.slice(start,source.indexOf(end,source.indexOf(marker,start))+end.length),ctx);
for(const region of ['head','chest','rightArm','leftArm','rightLeg','leftLeg']){
 const sim=new ctx.ArenaCombat(()=>.999),a=sim.fighters[5],v=sim.fighters[0];Object.assign(a,{x:0,z:1,angle:Math.PI,attackRegion:region,action:'attack'});Object.assign(v,{x:0,z:0,angle:0,guardRegion:region});sim.prepareGuard(v,true);assert.equal(sim.guard(a,v),true,region+' guard');v.stamina=100;v.guardRegion=region==='head'?'chest':'head';sim.prepareGuard(v,true);assert.equal(sim.guard(a,v),false,region+' wrong guard');
 v.guardRegion=null;v.hp=100;sim.damage(a,v,10,region);assert.ok(Number.isFinite(v.body[region]));if(region==='leftLeg')assert.equal(v.body.rightLeg,100);if(region==='rightLeg')assert.equal(v.body.leftLeg,100);
}
const ticket={id:'00000000-0000-4000-8000-000000000001',mode:'solo20',snapshot:{gladiator:{id:'g1',class:'secutor',name:'Secutor',overall:50},items:[]}};
const out=path.resolve(root,'../qa-v43');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+'/')||!fs.existsSync(file)){res.writeHead(404);return res.end();}let data=fs.readFileSync(file);if(file.endsWith('arena.html')){let html=data.toString();const a=html.indexOf('var LudusBattle='),b=html.indexOf('/* Poly Haven',a);html=html.slice(0,a)+`var LudusBattle={ticket:${JSON.stringify(ticket)},load:async()=>({}),finish:async()=>({})};\n`+html.slice(b);html=html.replace('mainMenu();Promise.all([LudusBattle.load()',"window.__arena={combat,camera,worldInput,clearInput,setPaused,get controls(){return touchControls;}};mainMenu();Promise.all([LudusBattle.load()");data=Buffer.from(html);}res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream','Content-Security-Policy':"connect-src 'self' blob: data:"});res.end(data);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/arena.html`);await page.waitForFunction(()=>window.__arena&&document.getElementById('intro').hidden,{timeout:90000});
 await page.evaluate(()=>{const c=__arena.combat;for(const f of c.fighters){f.cooldown=999;if(f.id!==0)f.hp=0;}const a=c.fighters[0],b=c.fighters[5];Object.assign(a,{x:0,z:0,angle:0,hp:120,action:'idle',cooldown:0,weapon:'gladius',shield:true,shieldHeldBy:null});Object.assign(b,{hp:100,x:0,z:-2.5,cooldown:999});c.finished=false;});
 const layouts=[];for(const [width,height]of [[667,375],[844,390],[932,430],[740,320],[1366,768]]){await page.setViewportSize({width,height});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const boxes=await page.locator('.body-target,#attack,#block,#dodge,#special').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{id:e.id||e.dataset.region,x:r.x,y:r.y,w:r.width,h:r.height};}));for(const b of boxes)assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=width&&b.y+b.h<=height,JSON.stringify(b));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'overlap '+a.id+' '+b.id);}layouts.push({width,height,boxes});}
 await page.setViewportSize({width:844,height:390});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:out+'/before-input.png'});await page.locator('#block').dispatchEvent('pointerdown',{pointerId:10});assert.equal(await page.locator('#block').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#attack').getAttribute('aria-pressed'),'false');
 // Real pointer capture: hold a region, then release it. A mode stays selected.
 const box=await page.locator('[data-region=head]').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();assert.equal(await page.evaluate(()=>__arena.worldInput().guardRegion),'head');await page.mouse.up();assert.equal(await page.evaluate(()=>__arena.worldInput().block),false);assert.equal(await page.locator('#block').getAttribute('aria-pressed'),'true');
 await page.locator('#attack').dispatchEvent('pointerdown',{pointerId:11});await page.evaluate(()=>{const p=__arena.combat.fighters[0];Object.assign(p,{hp:100,action:'idle',cooldown:0,stamina:100});});await page.locator('[data-region=leftLeg]').click();assert.equal(await page.evaluate(()=>__arena.combat.fighters[0].attackRegion),'leftLeg');
 await page.screenshot({path:out+'/arena.png'});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/report.json',JSON.stringify({layouts,errors,camera:await page.evaluate(()=>__arena.camera.position.toArray())},null,2));console.log('Six-region guard/damage, mode latching, pointer release, actual attack and five viewport layouts passed.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
