const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function runtime(page){const html=fs.readFileSync(path.join(__dirname,'..',page),'utf8'),ctx=vm.createContext({console});const start=html.indexOf('var ArenaClasses='),marker="if(typeof module!=='undefined')module.exports=install;else install(root.ArenaCombat,root.ArenaClasses);",ending="})(typeof window!=='undefined'?window:globalThis);",end=html.indexOf(ending,html.indexOf(marker,start))+ending.length;vm.runInContext(html.slice(start,end),ctx);const load=html.indexOf('var LudusLoadout='),finish=html.indexOf('})();',html.indexOf('P.damageProjectileV10=',load))+5;vm.runInContext(html.slice(load,finish).replace(/<\/script>[\s\S]*?<script[^>]*>/g,''),ctx);return ctx;}
function item(c,kind,enhancement=0,extras={}){return{stat_version:10,natural_rule_version:2,kind,model:kind==='weapon'?'gladius':kind,enhancement,natural_stats:c.LudusItemSystem.baseStats(kind),natural_percentages:{},emeralds:[],rubies:[],equipped_slot:kind==='weapon'?'main_hand':kind,...extras};}
for(const page of ['arena.html','savas.html','multiplayer.html']){
 const c=runtime(page),g={class:'secutor',overall:50,level:1};
 function hit(level,defense=[]){const sim=new c.ArenaCombat(()=>.999).reset('normal','secutor'),a=sim.fighters[0],b=sim.fighters[5];c.LudusLoadout.apply(a,g,[item(c,'weapon',level)]);c.LudusLoadout.apply(b,g,defense);b.maxHp=b.hp=10000;b.body.chest=100;const hp=b.hp;sim.damage(a,b,200,'chest',false);return hp-b.hp;}
 test(page+': +7 changes displayed physical power and real dealt damage',()=>{assert.equal(c.LudusItemSystem.effectiveStats(item(c,'weapon',0)).physical_power,7);assert.ok(Math.abs(c.LudusItemSystem.effectiveStats(item(c,'weapon',7)).physical_power-11.9)<1e-8);const base=hit(0),up=hit(7);assert.ok(up/base>1.65&&up/base<1.75,JSON.stringify({base,up}));});
 test(page+': upgraded armor reduces actual incoming damage',()=>{assert.ok(hit(7,[item(c,'chest',7)])<hit(7,[item(c,'chest',0)]));});
 test(page+': equipment supports health, stamina, movement and attack cadence',()=>{const sim=new c.ArenaCombat(()=>.999).reset('normal','secutor'),a=sim.fighters[0];c.LudusLoadout.apply(a,g,[]);const base={hp:a.maxHp,stamina:a.maxStamina,speed:a.speedBonus};c.LudusLoadout.apply(a,g,[item(c,'legs',7,{emeralds:[{id:1,value:100},{id:3,value:100},{id:15,value:100}]})]);assert.equal(a.maxHp,base.hp+20);assert.equal(a.maxStamina,base.stamina+20);assert.ok(a.speedBonus>base.speed);assert.equal(a.itemStats.attack_speed,4);sim.attack(0);const fast=a.duration;const other=new c.ArenaCombat(()=>.999).reset('normal','secutor');c.LudusLoadout.apply(other.fighters[0],g,[]);other.attack(0);assert.ok(fast<other.fighters[0].duration);});
}
test('analog middle walks and full stick walks briskly, without drift in the deadzone',()=>{const c=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'..','owner-gait-v30.js'),'utf8'),c);assert.equal(c.LudusGait.sample(.09).speed,0);assert.ok(c.LudusGait.sample(.5).speed>=1.4);assert.ok(Math.abs(c.LudusGait.sample(1).speed-2.6)<1e-8);assert.equal(c.LudusGait.sample(.6).run,0);for(let m=.1;m<1;m+=.01)assert.ok(c.LudusGait.sample(m+.01).speed>=c.LudusGait.sample(m).speed);});
